# .readthedocs.yaml
version: 2

build:
  tools:
    python: "3.12"
  os: ubuntu-22.04
  image: latest
  commands:
    - tox -e docs


python:
  version: "3.12"
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py