# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_build:
      - tox -e docs

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py