version: 2

python:
  version: "3.12"
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  image: latest
  commands:
    - tox -e docs
